export const DOMAIN = 'http://swp490g52-env.eba-sk7m9gfw.ap-southeast-1.elasticbeanstalk.com/api'
export const ORI_DOMAIN = 'http://swp490g52-env.eba-sk7m9gfw.ap-southeast-1.elasticbeanstalk.com'
export const GOOGLE_DISTANCE_API_URL = 'https://maps.googleapis.com/maps/api/distancematrix/json'
export const GOOGLE_MAP_SUGGEST_ADDRESS_API_URL = 'https://maps.googleapis.com/maps/api/place/textsearch/json'
// export const GOOGLE_DISTANCE_API_KEY = 'AIzaSyAtxeJgdr8kswb1dSkO7JJSkZ5uqobkMiQ'
export const GOOGLE_DISTANCE_API_KEY = 'AIzaSyDGc1fl09dTZGUP3-216W-yU3Nz0CNymVs'
// export const GOOGLE_MAP_API_KEY = 'AIzaSyAggadr7MGTYZfY63Y0FWibZ3tT9sLq-YM'
export const GOOGLE_MAP_API_KEY = 'AIzaSyCih4R71sFnB1efEK09Y21_4hEbPOQ25N0'